### ISSUE TITLE
Assignment 7

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/dsn1674-assignment-7#1]
For assignment 7, I assume that the navigation at the top of the mockup is supposed to be hyperlinked to buttons on each image near the bottom of the page, and the buttons only have a hover state correct?

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
The links need to have hover states, yes.
They can link down the page as you suggest, but that’s not necessary.
