### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/dsn1674-assignment-7#2]
Trying to get an opacity to happen in the nav and then a second one overlapping when it's hovered over.

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Try using `rgba()` instead of `opacity`.

**Comment by hldouglas** [comment]
I've done this, however, it's not showing up on the webpage.

**Comment by thomasjbradley** [comment]
There shouldn't be a space between the "a" and the "(" in `rgba()`.
